apiVersion: batch/v1
kind: Job
metadata:
  labels:
    stormforge.io/application: pet-clinic
    stormforge.io/experiment: pet-clinic-startup-000
    stormforge.io/objective: cost-vs-startup-time
    stormforge.io/scenario: pet-clinic-startup-time
    stormforge.io/trial: pet-clinic-startup-000-000
    stormforge.io/trial-role: trialRun
  name: pet-clinic-startup-000-000
  namespace: examples
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: pet-clinic-startup-000-000
        stormforge.io/application: pet-clinic
        stormforge.io/experiment: pet-clinic-startup-000
        stormforge.io/objective: cost-vs-startup-time
        stormforge.io/scenario: pet-clinic-startup-time
        stormforge.io/trial: pet-clinic-startup-000-000
        stormforge.io/trial-role: trialRun
    spec:
      containers:
      - env:
        - name: NAMESPACE
          value: examples
        - name: APP_NAME
          value: pet-clinic
        - name: CPU_REQUEST
          value: "300"
        - name: CPU_LIMIT
          value: "500"
        - name: MEMORY
          value: "1000"
        - name: PUSHGATEWAY_URL
          value: http://optimize-examples-prometheus:9091/metrics/job/trialRun/instance/pet-clinic-startup-000-000
        image: public.ecr.aws/stormforge/pt:startup-checker-latest
        imagePullPolicy: IfNotPresent
        name: startup-checker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      serviceAccountName: optimize-setup-sa
      securityContext: {}
      terminationGracePeriodSeconds: 30
