---
apiVersion: v1
kind: Pod
metadata:
  name: perftest
spec:
  containers:
  - name: perftest
    image: docker.io/bitnami/kafka:3.3.1
    command: ['/bin/sh', '-c', 'while :; do sleep 3600; done']

